//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopBanGiay.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class Giay
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Giay()
        {
            this.DatHang_ChiTiet = new HashSet<DatHang_ChiTiet>();
        }

        [Display(Name = "Mã giày")]
        public int ID { get; set; }

        [Display(Name = "Nhà sản xuất")]
        [Required(ErrorMessage = "Chưa chọn nhà sản xuất!")]
        public Nullable<int> NhaSanXuat_ID { get; set; }

        [Display(Name = "Loại giày")]
        [Required(ErrorMessage = "Chưa chọn loại giày!")]
        public Nullable<int> LoaiGiay_ID { get; set; }

        [Display(Name = "Tên giày")]
        [Required(ErrorMessage = "Tên giày không được bỏ trống!")]
        public string TenGiay { get; set; }

        [Display(Name = "Size")]
        [DisplayFormat(DataFormatString = "{0:N0}", ApplyFormatInEditMode = false)]
        [Required(ErrorMessage = "Size không được bỏ trống!")]
        public Nullable<int> Size { get; set; }

        [Display(Name = "Đơn giá")]
        [DisplayFormat(DataFormatString = "{0:N0}", ApplyFormatInEditMode = false)]
        [Required(ErrorMessage = "Đơn giá bản không được bỏ trống!")]
        public Nullable<int> DonGia { get; set; }

        [Display(Name = "Số lượng")]
        [Required(ErrorMessage = "Số lượng không được bỏ trống!")]
        public Nullable<int> SoLuong { get; set; }

        [Display(Name = "Hình ảnh")]
        public string HinhAnh { get; set; }
        [Display(Name = "Hình ảnh ")]
        public HttpPostedFileBase DuLieuHinhAnhBia { get; set; }

        [Display(Name = "Mô tả sách")]
        [DataType(DataType.MultilineText)]
        public string MoTa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DatHang_ChiTiet> DatHang_ChiTiet { get; set; }
        public virtual NhaSanXuat NhaSanXuat { get; set; }
        public virtual LoaiGiay LoaiGiay { get; set; }
    }
}
